// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/ansible.proto

package ansible_pb // import "github.com/yushihui/ansible-pb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type JobStatus int32

const (
	JobStatus_Pending JobStatus = 0
	JobStatus_Running JobStatus = 1
	JobStatus_Success JobStatus = 2
	JobStatus_Failed  JobStatus = 3
)

var JobStatus_name = map[int32]string{
	0: "Pending",
	1: "Running",
	2: "Success",
	3: "Failed",
}
var JobStatus_value = map[string]int32{
	"Pending": 0,
	"Running": 1,
	"Success": 2,
	"Failed":  3,
}

func (x JobStatus) String() string {
	return proto.EnumName(JobStatus_name, int32(x))
}
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ansible_d89bb580fa5a1cd0, []int{0}
}

type JobPriority int32

const (
	JobPriority_Low    JobPriority = 0
	JobPriority_Normal JobPriority = 1
	JobPriority_High   JobPriority = 2
	JobPriority_Higher JobPriority = 3
	JobPriority_Super  JobPriority = 4
)

var JobPriority_name = map[int32]string{
	0: "Low",
	1: "Normal",
	2: "High",
	3: "Higher",
	4: "Super",
}
var JobPriority_value = map[string]int32{
	"Low":    0,
	"Normal": 1,
	"High":   2,
	"Higher": 3,
	"Super":  4,
}

func (x JobPriority) String() string {
	return proto.EnumName(JobPriority_name, int32(x))
}
func (JobPriority) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ansible_d89bb580fa5a1cd0, []int{1}
}

type AnsibleJob struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Playbook             string      `protobuf:"bytes,3,opt,name=playbook,proto3" json:"playbook,omitempty"`
	PlaybookCotent       []byte      `protobuf:"bytes,4,opt,name=playbookCotent,proto3" json:"playbookCotent,omitempty"`
	InventoryContent     []byte      `protobuf:"bytes,5,opt,name=inventoryContent,proto3" json:"inventoryContent,omitempty"`
	JobPriority          JobPriority `protobuf:"varint,6,opt,name=jobPriority,proto3,enum=com.netbrain.rpc.ansible.JobPriority" json:"jobPriority,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AnsibleJob) Reset()         { *m = AnsibleJob{} }
func (m *AnsibleJob) String() string { return proto.CompactTextString(m) }
func (*AnsibleJob) ProtoMessage()    {}
func (*AnsibleJob) Descriptor() ([]byte, []int) {
	return fileDescriptor_ansible_d89bb580fa5a1cd0, []int{0}
}
func (m *AnsibleJob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnsibleJob.Unmarshal(m, b)
}
func (m *AnsibleJob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnsibleJob.Marshal(b, m, deterministic)
}
func (dst *AnsibleJob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnsibleJob.Merge(dst, src)
}
func (m *AnsibleJob) XXX_Size() int {
	return xxx_messageInfo_AnsibleJob.Size(m)
}
func (m *AnsibleJob) XXX_DiscardUnknown() {
	xxx_messageInfo_AnsibleJob.DiscardUnknown(m)
}

var xxx_messageInfo_AnsibleJob proto.InternalMessageInfo

func (m *AnsibleJob) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AnsibleJob) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AnsibleJob) GetPlaybook() string {
	if m != nil {
		return m.Playbook
	}
	return ""
}

func (m *AnsibleJob) GetPlaybookCotent() []byte {
	if m != nil {
		return m.PlaybookCotent
	}
	return nil
}

func (m *AnsibleJob) GetInventoryContent() []byte {
	if m != nil {
		return m.InventoryContent
	}
	return nil
}

func (m *AnsibleJob) GetJobPriority() JobPriority {
	if m != nil {
		return m.JobPriority
	}
	return JobPriority_Low
}

type AnsibleJobResponse struct {
	Message              string               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Status               JobStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=com.netbrain.rpc.ansible.JobStatus" json:"status,omitempty"`
	StartTime            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              *timestamp.Timestamp `protobuf:"bytes,4,opt,name=endTime,proto3" json:"endTime,omitempty"`
	ExeLog               []byte               `protobuf:"bytes,5,opt,name=exeLog,proto3" json:"exeLog,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AnsibleJobResponse) Reset()         { *m = AnsibleJobResponse{} }
func (m *AnsibleJobResponse) String() string { return proto.CompactTextString(m) }
func (*AnsibleJobResponse) ProtoMessage()    {}
func (*AnsibleJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ansible_d89bb580fa5a1cd0, []int{1}
}
func (m *AnsibleJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnsibleJobResponse.Unmarshal(m, b)
}
func (m *AnsibleJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnsibleJobResponse.Marshal(b, m, deterministic)
}
func (dst *AnsibleJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnsibleJobResponse.Merge(dst, src)
}
func (m *AnsibleJobResponse) XXX_Size() int {
	return xxx_messageInfo_AnsibleJobResponse.Size(m)
}
func (m *AnsibleJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AnsibleJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AnsibleJobResponse proto.InternalMessageInfo

func (m *AnsibleJobResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AnsibleJobResponse) GetStatus() JobStatus {
	if m != nil {
		return m.Status
	}
	return JobStatus_Pending
}

func (m *AnsibleJobResponse) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *AnsibleJobResponse) GetEndTime() *timestamp.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *AnsibleJobResponse) GetExeLog() []byte {
	if m != nil {
		return m.ExeLog
	}
	return nil
}

func init() {
	proto.RegisterType((*AnsibleJob)(nil), "com.netbrain.rpc.ansible.AnsibleJob")
	proto.RegisterType((*AnsibleJobResponse)(nil), "com.netbrain.rpc.ansible.AnsibleJobResponse")
	proto.RegisterEnum("com.netbrain.rpc.ansible.JobStatus", JobStatus_name, JobStatus_value)
	proto.RegisterEnum("com.netbrain.rpc.ansible.JobPriority", JobPriority_name, JobPriority_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AnsibleServiceClient is the client API for AnsibleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AnsibleServiceClient interface {
	StartAnsibleJob(ctx context.Context, in *AnsibleJob, opts ...grpc.CallOption) (AnsibleService_StartAnsibleJobClient, error)
}

type ansibleServiceClient struct {
	cc *grpc.ClientConn
}

func NewAnsibleServiceClient(cc *grpc.ClientConn) AnsibleServiceClient {
	return &ansibleServiceClient{cc}
}

func (c *ansibleServiceClient) StartAnsibleJob(ctx context.Context, in *AnsibleJob, opts ...grpc.CallOption) (AnsibleService_StartAnsibleJobClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AnsibleService_serviceDesc.Streams[0], "/com.netbrain.rpc.ansible.AnsibleService/StartAnsibleJob", opts...)
	if err != nil {
		return nil, err
	}
	x := &ansibleServiceStartAnsibleJobClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AnsibleService_StartAnsibleJobClient interface {
	Recv() (*AnsibleJobResponse, error)
	grpc.ClientStream
}

type ansibleServiceStartAnsibleJobClient struct {
	grpc.ClientStream
}

func (x *ansibleServiceStartAnsibleJobClient) Recv() (*AnsibleJobResponse, error) {
	m := new(AnsibleJobResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AnsibleServiceServer is the server API for AnsibleService service.
type AnsibleServiceServer interface {
	StartAnsibleJob(*AnsibleJob, AnsibleService_StartAnsibleJobServer) error
}

func RegisterAnsibleServiceServer(s *grpc.Server, srv AnsibleServiceServer) {
	s.RegisterService(&_AnsibleService_serviceDesc, srv)
}

func _AnsibleService_StartAnsibleJob_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AnsibleJob)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AnsibleServiceServer).StartAnsibleJob(m, &ansibleServiceStartAnsibleJobServer{stream})
}

type AnsibleService_StartAnsibleJobServer interface {
	Send(*AnsibleJobResponse) error
	grpc.ServerStream
}

type ansibleServiceStartAnsibleJobServer struct {
	grpc.ServerStream
}

func (x *ansibleServiceStartAnsibleJobServer) Send(m *AnsibleJobResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _AnsibleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.netbrain.rpc.ansible.AnsibleService",
	HandlerType: (*AnsibleServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartAnsibleJob",
			Handler:       _AnsibleService_StartAnsibleJob_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/ansible.proto",
}

func init() { proto.RegisterFile("proto/ansible.proto", fileDescriptor_ansible_d89bb580fa5a1cd0) }

var fileDescriptor_ansible_d89bb580fa5a1cd0 = []byte{
	// 480 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x5f, 0x8b, 0xd3, 0x4c,
	0x14, 0xc6, 0x3b, 0x6d, 0xb7, 0xdd, 0x9e, 0x2e, 0x7d, 0xc3, 0x79, 0x41, 0x42, 0x2f, 0xb4, 0xd4,
	0x3f, 0x94, 0xa2, 0xa9, 0x54, 0x2f, 0x04, 0x41, 0x70, 0x0b, 0x2a, 0x65, 0x91, 0x92, 0xee, 0x95,
	0x77, 0x93, 0xe6, 0x98, 0x8e, 0x26, 0x33, 0x61, 0x66, 0xb2, 0x5a, 0xfc, 0xc4, 0x5e, 0xfb, 0x05,
	0x24, 0xd3, 0x64, 0x5b, 0x94, 0xaa, 0x77, 0xe7, 0x39, 0xf9, 0x3d, 0x4c, 0xce, 0x73, 0x66, 0xe0,
	0xff, 0x5c, 0x2b, 0xab, 0x66, 0x5c, 0x1a, 0x11, 0xa5, 0x14, 0x38, 0x85, 0xfe, 0x46, 0x65, 0x81,
	0x24, 0x1b, 0x69, 0x2e, 0x64, 0xa0, 0xf3, 0x4d, 0x50, 0x7d, 0x1f, 0xde, 0x4b, 0x94, 0x4a, 0x52,
	0x9a, 0x39, 0x2e, 0x2a, 0x3e, 0xce, 0xac, 0xc8, 0xc8, 0x58, 0x9e, 0xe5, 0x7b, 0xeb, 0xf8, 0x3b,
	0x03, 0x78, 0xbd, 0x87, 0x97, 0x2a, 0xc2, 0x01, 0x34, 0x45, 0xec, 0xb3, 0x11, 0x9b, 0xf4, 0xc2,
	0xa6, 0x88, 0x11, 0xa1, 0x2d, 0x79, 0x46, 0x7e, 0xd3, 0x75, 0x5c, 0x8d, 0x43, 0x38, 0xcf, 0x53,
	0xbe, 0x8b, 0x94, 0xfa, 0xec, 0xb7, 0x5c, 0xff, 0x56, 0xe3, 0x23, 0x18, 0xd4, 0xf5, 0x42, 0x59,
	0x92, 0xd6, 0x6f, 0x8f, 0xd8, 0xe4, 0x22, 0xfc, 0xa5, 0x8b, 0x53, 0xf0, 0x84, 0xbc, 0x21, 0x69,
	0x95, 0xde, 0x2d, 0x94, 0x74, 0xe4, 0x99, 0x23, 0x7f, 0xeb, 0xe3, 0x5b, 0xe8, 0x7f, 0x52, 0xd1,
	0x4a, 0x0b, 0xa5, 0x85, 0xdd, 0xf9, 0x9d, 0x11, 0x9b, 0x0c, 0xe6, 0x0f, 0x83, 0x53, 0x33, 0x07,
	0xcb, 0x03, 0x1c, 0x1e, 0x3b, 0xc7, 0x3f, 0x18, 0xe0, 0x61, 0xd6, 0x90, 0x4c, 0xae, 0xa4, 0x21,
	0xf4, 0xa1, 0x9b, 0x91, 0x31, 0x3c, 0xa1, 0x6a, 0xf0, 0x5a, 0xe2, 0x4b, 0xe8, 0x18, 0xcb, 0x6d,
	0x61, 0xdc, 0xfc, 0x83, 0xf9, 0xfd, 0x3f, 0x1e, 0xba, 0x76, 0x68, 0x58, 0x59, 0xf0, 0x05, 0xf4,
	0x8c, 0xe5, 0xda, 0x5e, 0x8b, 0x8c, 0x5c, 0x4e, 0xfd, 0xf9, 0x30, 0xd8, 0xaf, 0x23, 0xa8, 0xd7,
	0x11, 0x5c, 0xd7, 0xeb, 0x08, 0x0f, 0x30, 0x3e, 0x87, 0x2e, 0xc9, 0xd8, 0xf9, 0xda, 0x7f, 0xf5,
	0xd5, 0x28, 0xde, 0x81, 0x0e, 0x7d, 0xa5, 0x2b, 0x95, 0x54, 0x41, 0x56, 0x6a, 0xfa, 0x0a, 0x7a,
	0xb7, 0x3f, 0x87, 0x7d, 0xe8, 0xae, 0x48, 0xc6, 0x42, 0x26, 0x5e, 0xa3, 0x14, 0x61, 0x21, 0x65,
	0x29, 0x58, 0x29, 0xd6, 0xc5, 0x66, 0x43, 0xc6, 0x78, 0x4d, 0x04, 0xe8, 0xbc, 0xe1, 0x22, 0xa5,
	0xd8, 0x6b, 0x4d, 0x17, 0xd0, 0x3f, 0x4a, 0x14, 0xbb, 0xd0, 0xba, 0x52, 0x5f, 0xbc, 0x46, 0xc9,
	0xbc, 0x57, 0x3a, 0xe3, 0xa9, 0xc7, 0xf0, 0x1c, 0xda, 0xef, 0x44, 0xb2, 0xdd, 0x3b, 0xcb, 0x8a,
	0xb4, 0xd7, 0xc2, 0x1e, 0x9c, 0xad, 0x8b, 0x9c, 0xb4, 0xd7, 0x9e, 0x7f, 0x83, 0x41, 0x95, 0xfc,
	0x9a, 0xf4, 0x8d, 0xd8, 0x10, 0x0a, 0xf8, 0x6f, 0x5d, 0x4e, 0x7c, 0x74, 0xf9, 0x1e, 0x9c, 0x8e,
	0xf7, 0x40, 0x0d, 0x1f, 0xff, 0x0b, 0x55, 0x2f, 0x77, 0xdc, 0x78, 0xca, 0x2e, 0x97, 0x70, 0xf2,
	0x81, 0x5c, 0x5e, 0x54, 0x9e, 0x55, 0x99, 0xec, 0x8a, 0x7d, 0xb8, 0x9b, 0x08, 0xbb, 0x2d, 0xa2,
	0xf2, 0x8c, 0xd9, 0xae, 0x30, 0x5b, 0xb1, 0x2d, 0x44, 0xfd, 0xda, 0x9e, 0xe4, 0x51, 0xd4, 0x71,
	0x2b, 0x78, 0xf6, 0x33, 0x00, 0x00, 0xff, 0xff, 0x3d, 0xe6, 0xc2, 0xa6, 0x88, 0x03, 0x00, 0x00,
}
